//pncquestions
let pncQueDB = [
  {
    question: "Two pipes A & B can fill the tank in 12 hours and 36 hours respectively. If both the pipes are opened simultaneously, how much time will be required to fill the tank?",
    a: "6 hours",
    b: "9 hours",
    c: "12 hours",
    d: "15 hours",
    ans: "ans2",
  },
  {
    question: "Two pipes can fill a tank in 6 hours and 8 hours respectively while a third pipe empties the full tank in 12 hours. If all the three pipes operate simultaneously, in how much time will the tank be filled?",
    a: "7(1/2) hrs",
    b: "4(4/5) hrs",
    c: "3 (2/7) hrs",
    d: "1(1/5) hrs",
    ans: "ans2",
  },
  {
    question: "Two pipes can fill a tank in 10 and 14 minutes respectively and a waste pipe can empty 4 gallons per minute. If all the pipes working together can fill the tank in 6 minutes, what is the capacity of the tank?",
    a: "120 gallons",
    b: "240 gallons",
    c: "450 gallons",
    d: "840 gallons",
    ans: "ans4",
  },
  {
    question: "A booster pump can be used to fill as to empty the tank. The capacity of the tank is 1200 m3. The emptying capacity of the tank is 10 m3 per minute higher than its filling capacity and the pump requires 4 minutes lesser to vacant the tank than it requires to fill it. Calculate the filling capacity of the pump.",
    a: "25",
    b: "50",
    c: "75",
    d: "100",
    ans: "ans2",
  },
  {
    question: "An electric pump can fill a tank in 4 hours. Due to leakage in the tank, it took 4(1/2) hrs to fill the tank. If the tank is full, how much time will the leak take to empty the full tank?",
    a: "8",
    b: "16",
    c: "21",
    d: "36",
    ans: "ans4",
  },
  {
    question: "Two pipes fills a cistern in 15 hrs and 20 hrs respectively. The pipes are opened simultaneously and it is observed that it took 26 min more to fill the cistern because of leakage at the bottom. If the cistern is full, then in what time will the leak empty it?",
    a: "30",
    b: "75",
    c: "180",
    d: "300",
    ans: "ans3",
  },
  {
    question: "If two pipes function simultaneously, the reservoir will be filled in 24 hrs. One pipe fills the reservoir 20 hours faster than the other. How many hours does it take for the second pipe to fill the reservoir?",
    a: "12",
    b: "30",
    c: "44",
    d: "60",
    ans: "ans4",
  },
  {
    question: "Two pipes can fill a tank in 8 hrs & 6 hrs respectively. If they are opened on alternate hours and if pipe A gets opened first, then in how many hours, the tank will be full?",
    a: "6",
    b: "7",
    c: "8",
    d: "14",
    ans: "ans2",
  },
  {
    question: "It is observed that the pipe A can fill the tank in 15 hrs and the same tank is filled by pipe B in 20 hrs. The third pipe C can vacant the tank in 25 hrs. If all the pipes get opened initially and after 10 hrs, the pipe C is closed, then how long will it take to fill the tank?",
    a: "3",
    b: "7",
    c: "12",
    d: "20",
    ans: "ans3",
  },
  {
    question: "Two pipes A & B can fill a tank in 5 min & 10 min respectively. Both the pipes are opened together but after 2 min, pipe A is turned off. What is the total time required to fill the tank?",
    a: "4",
    b: "6",
    c: "14",
    d: "20",
    ans: "ans2",
  },
];

//proablity questions
let pbbQueDB = [
  {
    question: "Three unbiased coins are tossed. What is the probability of getting at least 2 tails?",
    a: "0.75",
    b: "0.5",
    c: "0.25",
    d: "0.2",
    ans: "ans2",
  },
  {
    question: "Tickets numbered 1 to 50 are mixed and one ticket is drawn at random. Find the probability that the ticket drawn has a number which is a multiple of 4 or 7?",
    a: "9/25",
    b: "9/50",
    c: "18/25",
    d: "None of these",
    ans: "ans1",
  },
  {
    question: "From a pack of 52 cards, one card is drawn at random. Find the probability that the drawn card is a club or a jack?",
    a: "17/52",
    b: "8/13",
    c: "4/13",
    d: "1/13",
    ans: "ans3",
  },
  {
    question: "Two friends A and B apply for a job in the same company. The chances of A getting selected is 2/5 and that of B is 4/7. What is the probability that both of them get selected?",
    a: "8/35",
    b: "34/35",
    c: "27/35",
    d: "None of these",
    ans: "ans1",
  },
  {
    question: "The probability of event equal to zero is called;",
    a: "Unsure event",
    b: "Sure Event",
    c: "Impossible event",
    d: "Independent event",
    ans: "ans3",
  },
  {
    question: "The probability that cannot exist among the following:",
    a: "⅔",
    b: "-1.5",
    c: "15%",
    d: "0.7",
    ans: "ans2",
  },
  {
    question: "If P(E) = 0.07, then what is the probability of ‘not E’?",
    a: "0.93",
    b: "0.95",
    c: "0.89",
    d: "0.90",
    ans: "ans1",
  },
  {
    question: "A bag has 3 red balls and 5 green balls. If we take a ball from the bag, then what is the probability of getting red balls only?",
    a: "3",
    b: "8",
    c: "3/8",
    d: "8/3",
    ans: "ans3",
  },
  {
    question: "A bag has 5 white marbles, 8 red marbles and 4 purple marbles. If we take a marble randomly, then what is the probability of not getting purple marble?",
    a: "0.5",
    b: "0.66",
    c: "0.08",
    d: "0.77",
    ans: "ans4",
  },
  {
    question: "A dice is thrown in the air. The probability of getting odd numbers is",
    a: "1/2",
    b: "3/2",
    c: "3",
    d: "4",
    ans: "ans1",
  },
];

//problems on ages
let poaQueDB = [
  {
    question: "What is John’s present age, if after 10 years his age will be 5 times his age 5 years back.",
    a: "6.2 years",
    b: "7.7 years",
    c: "8.7 years",
    d: "10 years",
    ans: "ans3",
  },
  {
    question: "Rahul is 15 years elder than Rohan. If 5 years ago, Rahul was 3 times as old as Rohan, then find Rahul's present age.",
    a: "32.5",
    b: "27.5",
    c: "25",
    d: "24.9",
    ans: "ans2",
  },
  {
    question: "One year ago, ratio of Harry and Peter age’s was 5 : 6 respectively. After 4 years, this ratio becomes 6 : 7. How old is Peter?",
    a: "25",
    b: "26",
    c: "31",
    d: "35",
    ans: "ans3",
  },
  {
    question: "Age of mother 10 years ago was 3 times the age of her son. After 10 years, mother’s age will be twice that of his son. Find the ratio of their present ages.",
    a: "11 : 7",
    b: "9 : 5",
    c: "7 : 4",
    d: "7 : 3",
    ans: "ans4",
  },
  {
    question: "Sharad is 60 years old and Santosh is 80 years old. How many years ago was the ratio of their ages 4 : 6?",
    a: "10 years",
    b: "15 years",
    c: "20 years",
    d: "25 years",
    ans: "ans3",
  },
  {
    question: "The ratio of Rohan’s age 4 years ago and Rahul’s age after 4 years is 1 : 1. If at present, the ratio of their ages is 5 : 3, then find the ratio between Rohan’s age 4 years hence and Rahul’s age 4 years ago.",
    a: "1 : 3",
    b: "3 : 1",
    c: "4 : 3",
    d: "3 : 4",
    ans: "ans2",
  },
  {
    question: "5 years ago, sister’s age was 5 times the age of her brother and the sum of present ages of sister and brother is 34 years. What will be the age of her brother after 6 years?",
    a: "12 years",
    b: "13.5 years",
    c: "15 years",
    d: "20 years",
    ans: "ans3",
  },
  {
    question: "Father is 3 times more aged than his daughter. If after 5 years, he would be 3 times of daughter’s age, then further after 5 years, how many times he would be of his daughter’s age?",
    a: "1 (½) times",
    b: "2 times",
    c: "2.5 times",
    d: "3 times",
    ans: "ans3",
  },
  {
    question: "The sum of ages of 5 children born at the intervals of 3 years each is 50 years. What is the age of the youngest child?",
    a: "4 years",
    b: "8 years",
    c: "10 years",
    d: "None of these",
    ans: "ans1",
  },
  {
    question: "A is two years older than B who is twice as old as C. If the total of the ages of A, B and C be 27, then how old is B?",
    a: "7",
    b: "8",
    c: "9",
    d: "10",
    ans: "ans4",
  },
];

//profit and loss questions
let plQueDB = [
  {
    question: "A shopkeeper sells an article for Rs. 200 with a loss of Rs. 20 %. Find the cost price of the article.",
    a: "220",
    b: "250",
    c: "280",
    d: "260",
    ans: "ans2",
  },
  {
    question: "A trader expects a gain of 15 % on his cost price. If in a week his sale is of Rs. 580, then what is his profit?",
    a: "75.65",
    b: "73.26",
    c: "72.50",
    d: "70.78",
    ans: "ans1",
  },
  {
    question: "If a boy sells a book for Rs. 450 he gets a loss of 10 %, then find cost price. To gain 10 %, what should be the selling price?",
    a: "400, 500",
    b: "550, 600",
    c: "500, 550",
    d: "475, 525",
    ans: "ans3",
  },
  {
    question: "A merchant sells 30 metres of cloth and gains selling price of 10 metres. Find the gain percent.",
    a: "15 %",
    b: "25 %",
    c: "50 %",
    d: "75%",
    ans: "ans3",
  },
  {
    question: "S.P. of 10 candles is same as C.P. of 12 candles. Find the gain percent.",
    a: "11 %", 
    b: "15 %",
    c: "20 %",
    d: "25 %,",
    ans: "ans3",
  },
  {
    question: "The selling price of 40 apples is equal to cost price of 35 apples. Find the profit or loss obtained",
    a: "Gain of 5.5 %",
    b: "Gain of 12.5 %",
    c: "Loss of 5.5 %",
    d: "Loss of 12.5 %",
    ans: "ans4",
  },
  {
    question: "A man purchased two plots for Rs. 5,00,000. On one he gains 15 % while on the other he losses 15%. Find how much does he gain or lose in the transaction.",
    a: "1.5 %",
    b: "2 %",
    c: "2.25 %",
    d: "2.50 %",
    ans: "ans3",
  },
  {
    question: "A boy bought camel and carriage for Rs. 5000. He sells the camel at a gain of 20% and the carriage at a loss of 10%. If he gains 3% on the whole, then find the cost of the camel.",
    a: "2170",
    b: "2400",
    c: "2315",
    d: "2600",
    ans: "ans1",
  },
  {
    question: "A man sells one camera A for Rs. 7500 at a gain of 20% and another camera B for Rs. 8550 at a loss of 5 %. Find his total loss or gain%.",
    a: "2.7 %",
    b: "5.2 %",
    c: "4.2 %",
    d: "5.1 %",
    ans: "ans2",
  },
  {
    question: "A shopkeeper sells his goods at cost price but uses a weight of 970 grams for a kg. weight. What is his gain percent?",
    a: "5.08 %",
    b: "4.23 %",
    c: "3.26 %",
    d: "3.09 %",
    ans: "ans4",
  },
];
